version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node-polkadot:
    image: onfinality/subql-node:v1.21.2
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-polkadot.yaml
      - --multi-chain
      - --db-schema=app
      - --disable-historical
      - --query-limit=1000000
      - --batch-size=30
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node-polkadot:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-kusama:
    image: onfinality/subql-node:v1.21.2
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-kusama.yaml
      - --multi-chain
      - --db-schema=app
      - --disable-historical
      - --query-limit=1000000
      - --batch-size=30
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://subquery-node-kusama:3000/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-moonbeam:
    image: onfinality/subql-node:v1.21.2
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-moonbeam.yaml
      - --multi-chain
      - --db-schema=app
      - --disable-historical
      - --query-limit=1000000
      - --batch-size=30
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://subquery-node-moonbeam:3000/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-moonriver:
    image: onfinality/subql-node:v1.21.2
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-moonriver.yaml
      - --multi-chain
      - --db-schema=app
      - --disable-historical
      - --query-limit=1000000
      - --batch-size=30
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://subquery-node-moonriver:3000/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-aleph-zero:
    image: onfinality/subql-node:v1.21.2
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-aleph-zero.yaml
      - --multi-chain
      - --db-schema=app
      - --disable-historical
      - --query-limit=1000000
      - --batch-size=30
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://subquery-node-aleph-zero:3000/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-zeitgeist:
    image: onfinality/subql-node:v1.21.2
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-zeitgeist.yaml
      - --multi-chain
      - --db-schema=app
      - --disable-historical
      - --query-limit=1000000
      - --batch-size=30
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://subquery-node-zeitgeist:3000/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10
  
  subquery-node-westend:
    image: onfinality/subql-node:v1.21.2
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-westend.yaml
      - --multi-chain
      - --db-schema=app
      - --disable-historical
      - --query-limit=1000000
      - --batch-size=30
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://subquery-node-westend:3000/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-turing:
    image: onfinality/subql-node:v1.21.2
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-turing.yaml
      - --multi-chain
      - --db-schema=app
      - --disable-historical
      - --query-limit=1000000
      - --batch-size=30
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://subquery-node-turing:3000/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10
  
  subquery-node-calamari:
    image: onfinality/subql-node:v1.21.2
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-calamari.yaml
      - --multi-chain
      - --db-schema=app
      - --disable-historical
      - --query-limit=1000000
      - --batch-size=30
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://subquery-node-calamari:3000/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:latest
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --header 'Content-Type: application/json' \
            --post-data '{\"query\":\"\\n{\\n    stakingApies {\\n       nodes {\\n            networkId\\n            stakingType\\n            maxAPY\\n        }\\n    }\\n}\\n\",\"variables\":{}}' \
            --output-document=- http://127.0.0.1:3000 >/dev/null || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 2
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
    
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
